---

name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - release
  schedule:
    - cron: '0 1 * * *'
jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      -
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install
        run: yarn install --frozen-lockfile
  ci:
    strategy:
      matrix:
        node:
          - '12.x'
          - '14.x'
    runs-on: ubuntu-latest
    steps:
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      -
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install
        run: yarn install --frozen-lockfile
      - name: test
        run: yarn test:ci
      - name: save coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage-${{ matrix.node }}
          path: ./coverage
      - name: build
        run: yarn build
      - name: generate docs
        run: yarn docs
        if: matrix.node == '14.x' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release')
      - name: save docs
        if: matrix.node == '14.x' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release')
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ./docs
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      -
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install
        run: yarn install --frozen-lockfile
      - name: lint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ github.token }}
          reporter: 'github-pr-check'
  coverage:
    needs: ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - '12.x'
          - '14.x'
    steps:
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      -
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install
        run: yarn install --frozen-lockfile
      - name: download coverage artifact
        uses: actions/download-artifact@v2
        with:
          name: coverage-${{ matrix.node }}
          path: ./coverage
      - name: upload coverage
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  docs:
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'
    steps:
      - name: download docs artifact
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: ./docs
      - name: publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./docs
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
  release:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      -
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install
        run: yarn install --frozen-lockfile
      - name: build
        run: yarn build
      - name: release
        run: yarn semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
  create-release-pull-request:
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release
      - run: |
          git fetch origin main:main
          git reset --hard main
      - name: create release pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ github.token }}
          title: Next stable release candidate
          base: release
